### PR TITLE
Adding support for multiple navigation views in the tabbar

### PR DESCRIPTION
**Pull request by KyleLeneau**
Fixes: https://github.com/Dimillian/ACHNBrowserUI/issues/78

Also fixes so the view goes under the status bar.

### CODE REVIEW

**Comment by Dimillian** [comment]
It totally fix the issues yes, but I'm not sure I'm ready to replace a SwiftUI component by a UIKit wrapper. It's philosophical at this point haha. Let me play with it a bit and I'll see.

**Comment by KyleLeneau** [comment]
@Dimillian What is the goal you are trying to go for here? Keep only SwiftUI or make an app people will want to use and evolve with? I think this solution is aligned with either of those goals since using UIKit like this is part of SwiftUI design. There are many shortcomings of SwiftUI from my experience and I expect it to take Apple 1 or 2 more releases until developers consider it really ready (look at Swift, major adoption didn't come till 2.0 and 3.0).

If you don't decide to go with this approach then there is a tiny fix you can make to go under the status bar (`.edgesExtendedSafeInsets(.top)` I think...), put that on the TabBar view to take up the whole `UIWindow`.

**Comment by Dimillian** [comment]
I want to keep it mostly raw SwiftUI if I can. And the current component is not idea but it works okay, we’ll see this summer how it evolves. 
Also you should try your PR on Catalyst for some reason it make it crash even more :/

Where do you see an issue with the statusbar? I thought we solved that a while ago. 

Thanks!

**Comment by ericlewis** [comment]
I think I am going to close this for now @KyleLeneau, once we are sure apple has done nothing to fix this in 2.0 of SwiftUI then we can revisit. 

It is true we aim for a pure SwiftUI implementation, while this project is absolutely useful to people for real, it is primarily a teaching tool around SwiftUI as well as a demonstration project for what it can do. When it fails, it serves as an example to the folks at Apple. We are invested in SwiftUI becoming great.

I really appreciate this contribution, and it is exactly the solution we had discussed internally. I do hope you contribute more too!

**Comment by Dimillian** [comment]
As we stated here https://github.com/Dimillian/ACHNBrowserUI/pull/96
We'll not put the UIKit component even if it solves all our problem. This is not the philosophy of this project :)

**Comment by jerryturcios08** [comment]
> We'll not put the UIKit component even if it solves all our problem.

What about the following lines of code in SceneDelegate.swift?

```swift
UINavigationBar.appearance().largeTitleTextAttributes = [
    NSAttributedString.Key.font:UIFont.init(descriptor: descriptor2!, size: 34),
    NSAttributedString.Key.foregroundColor: UIColor(named: "ACText")!
]

UINavigationBar.appearance().titleTextAttributes = [
    NSAttributedString.Key.font:UIFont.init(descriptor: descriptor!, size: 17),
    NSAttributedString.Key.foregroundColor: UIColor(named: "ACText")!
]
            
UINavigationBar.appearance().barTintColor = UIColor(named: "ACSecondaryBackground")
UINavigationBar.appearance().backgroundColor = UIColor(named: "ACBackground")
UINavigationBar.appearance().tintColor = UIColor(named: "ACText")
            
UITableView.appearance().backgroundColor = UIColor(named: "ACBackground")
UITableViewCell.appearance().backgroundColor = UIColor(named: "ACSecondaryBackground")
UITableView.appearance().tableFooterView = UIView()
            
UITabBar.appearance().unselectedItemTintColor = UIColor(named: "TabLabel")
UITabBar.appearance().barTintColor = UIColor(named: "ACTabBarTint")
UITabBar.appearance().backgroundColor = UIColor(named: "ACTabBarTint")
```

Does this not count as using a UIKit component in order to allow you to solve a problem such as customizing the colors of the tab bar, navigation bar, etc.?

**Comment by Dimillian** [comment]
Well actually nop. It's the only way to style some SwiftUI components for now. But we have a Tabview in SwiftUI, hence why we'll not use the UIKit one.

**Comment by jerryturcios08** [comment]
@Dimillian Understood. Did you checkout [StatefulTabView](https://github.com/NicholasBellucci/StatefulTabView)? I played around with it, and I thought it solved the navigation reset issue for the TabView very nicely with some color customization options added.

**Pull request closed without merging**
