### PR TITLE
Update to Italian translation of Dodo Code

### PR DESCRIPTION
**Pull request by MrOgeid**
Translated new strings for Dodo Code notification.

### CODE REVIEW

**Comment by TheVaan** [comment]
Thank you. By the way: I fixed Italian translation so it should be in the next update. Sorry there for! I didn't checked that file good enough.

**Comment by MrOgeid** [comment]
I did some mistakes in the file? I checked and I didn’t find problems with spaces or quotation marks... so I don’t know how that happened.

**Comment by TheVaan** [comment]
There was missing a `;` - I don’t know if you missed it or we. No problem! I added a check for that in our build pipeline. I hope this will prevent us from releasing with bugs in localization.

**Comment by MrOgeid** [comment]
I found the missing `;`. It was my fault! I'm very sorry!
Is there something in Visual Studio Code that I can do to check that every string is correctly formatted? I don't want to add more problems to your work :-)

**Comment by TheVaan** [comment]
Are you in windows or on Mac OS?

**Comment by MrOgeid** [comment]
Mac OS

**Comment by TheVaan** [comment]
You have two options:

1. Install Xcode from App Store, open the project, edit language there (you will find it in project browser under "Localizable.strings", it unfolds and there you'll find Italian) and test it by pressing on the play button in the headline of Xcode. Then a simulator boots up. It will load a build of AC Helper. Go to simulator iOS Settings (on the first home screen), change language, kill AC Helper app in simulator and start again (changing language is only needed the first time you use the simulator).

2. Run `plutil -lint Localizable.strings` in Terminal (Mac OS Terminal or Visual Studio Code Terminal) inside the it.lproj folder - to run this, you may need to install xcode-command-line-tools. Terminal will guide you how to install.

If you choose the first way, you will have the benefit of testing your new translation if it feels good how you did.
If you choose the second way, you will get an output in terminal like: `Localizable.strings: OK` or a message that says in which line something is missing.

If you have further question feel free to contact me on twitter (my name there is @TheVaan, too)

**Comment by MrOgeid** [comment]
Thank you very much!! I'll try your solutions!

**Pull request merged**
