### PR TITLE
Italian localization

### PR DESCRIPTION
**Pull request by MrOgeid**
Italian localization of InfoPlist.strings and Localizable.strings

### CODE REVIEW

**Comment by Dimillian** [comment]
Simulator Screen Shot - iPhone 8 - 2020-05-25 at 17 52 59
Simulator Screen Shot - iPhone 8 - 2020-05-25 at 17 53 04

Congrats! We're now fully in Italian! This is so awesome!

**Comment by MrOgeid** [comment]
Awesome!👍 Let me know if in the future there'll be new strings to translate.

**Comment by Dimillian** [comment]
@MrOgeid You already have some new one after your island

```
"From 6pm to 5am" = "Von 18 bis 5 Uhr";
"From 8pm to 5am" = "Von 20 bis 5 Uhr";
"From 5am to 12pm" = "Von 5 bis 0 Uhr";

//Special characters
"K.K Slider" = "K.K. Slider";
"Daisy Mae" = "Jorna";
"C.J" = "Lomeus";
"Flick" = "Carlson";
"Kicks" = "Schubert";
"Saharah" = "Aziza";
"Label" = "Minna";
"Leif" = "Gerd";
"Redd" = "Reiner";
"Wisp" = "Buh";
"Celeste" = "Eufemia";

// Added 2020-05-23
"Museum Day" = "Internationaler Museumstag";
"Wedding Season" = "Hochzeitssaison";
"Bug-Off contest" = "Insektikus-Turnier";
"Meteor shower" =  "Sternschnuppen";

// Added 2020-05-23
"Reset" = "Zurücksetzen";
"View Turnip.Exchange islands" = "Zeige Turnip.Exchange Inseln";
"View on TurnipProphet" = "Auf TurnipProphet ansehen";

// Added 2020-05-24
"Music player" = "Musikplayer";
"Tracks" = "Lieder";
```

**Comment by MrOgeid** [comment]
Sorry, I haven't a lot of knowledge of Github functions: I added and translated these strings to Localizable.strings in my fork. I have to make another pull request?

**Comment by Dimillian** [comment]
Just send them to me here I'll integrate them. For the future the best is to delete your fork and start a new one :)

**Comment by MrOgeid** [comment]
Here it is! Next time I'll try to delete and start a new fork.

```
"From 6pm to 5am" = "Dalle 18:00 alle 05:00";
"From 8pm to 5am" = "Dalle 20:00 alle 05:00";
"From 5am to 12pm" = "Dalle 05:00 alle 12:00";

//Special characters
"K.K Slider" = "K.K. Slider";
"Daisy Mae" = "Brunella";
"C.J" = "Castorino";
"Flick" = "Ivano";
"Kicks" = "Sciuscià";
"Saharah" = "Sahara";
"Label" = "Beatrice";
"Leif" = "Florindo";
"Redd" = "Volpolo";
"Wisp" = "Spirideo";
"Celeste" = "Celeste";

// Added 2020-05-23
"Museum Day" = "Giornata internazionale dei musei";
"Wedding Season" = "Stagione dei matrimoni";
"Bug-Off contest" = "Insettomania";
"Meteor shower" =  "Pioggia di stelle";

// Added 2020-05-23
"Reset" = "Reimposta";
"View Turnip.Exchange islands" = "Guarda isole Turnip.Exchange";
"View on TurnipProphet" = "Guarda su TurnipProphet";

// Added 2020-05-24
"Music player" = "Player musicale";
"Tracks" = "Brani";
```

**Pull request merged**
