### PR TITLE
Fixed Italian localization

### PR DESCRIPTION
**Pull request by MrOgeid**
Fixed Italian localization for the legacy branch.

### CODE REVIEW

**Comment by TheVaan** [comment]
Will be in next update, if there is one 😁

**Comment by Dimillian** [comment]
Just to catch up, it’s also on main?

**Comment by MrOgeid** [comment]
> Just to catch up, it’s also on main?

Yes it is: I updated first the main branch... I thought that was enough but I saw that the recent updates didn't have the new localization for the Italian language so I updated the legacy branch too. I'm not sure this was needed. Do I have to update both branches next time?

**Comment by Dimillian** [comment]
So legacy branch is the one used for the App Store until iOS 14 come out of beta. So yeah will need to keep both branches updated for now :)

**Comment by MrOgeid** [comment]
Ok! No problem! From now on I'll update both branches! Thank you for the clarification!

**Pull request merged**
