### PR TITLE
Add notifications section in settings

### PR DESCRIPTION
**Pull request by rohanrk**
Issue: #25 

WIP PR to add push notifications and notifications settings in the app settings menu.

In Progress
- Notifications for when Nook's Cranny and Able Sisters open and close
- Toggle to verify if island time is synced with device time

TODO
- Notifications for special events
- Add toggles for other push notifications

@TheVaan

### CODE REVIEW

**Comment by TheVaan** [comment]
I would appreciate moving settings from section widget to section view. It’s not really user friendly putting settings in a widget.

**Comment by rohanrk** [comment]
I don't quite follow. Do you mean put all the sections in a single table separated by sections?

**Comment by TheVaan** [comment]
@rohanrk Oh my god. Sorry! I read this PR right after I woke up. My brain mixed up a few things. You've done everything right! Forget my comment 😆

**Comment by rohanrk** [comment]
Closing this in favor of #256

**Pull request closed without merging**
