### PR TITLE
Launch Screen Xib & Logo

### PR DESCRIPTION
**Pull request by eangele1**
Added a new xib file with custom logo so that launch screen will be displayed properly for all devices with compatible OS. Logo can be replaced with anything else.

### CODE REVIEW

**Comment by Dimillian** [comment]
Great job! But I think it should be one of our icon at least. And we never say on purpose Animal Crossing for legal reason :)

**Comment by eangele1** [comment]
Understood! Image has been updated.

**Comment by eangele1** [comment]
Not sure why but GitHub detected that my fork had conflicts with the base branch. Tried to resolve it but ended up breaking the build. Reverted the last commit and seems to be working normal now.

**Comment by Dimillian** [comment]
I think you should start fresh. If you look in the change you erase a bunch of changes on master :/

**Comment by eangele1** [comment]
Yeah was afraid that would be the case. No matter, I'll re-clone and start a new pull request.

**Pull request closed without merging**
