### PR TITLE
Add Italian translations for custom tasks

### PR DESCRIPTION
**Pull request by MrOgeid**
I added new translations for custom tasks as seen in the French and German file. 
I noticed that this time the file was partially in Spanish.😖 I don't know why. But I restored the Italian strings and corrected some typos. I added also some missing strings.

### CODE REVIEW

**Comment by TheVaan** [comment]
I‘m so sorry! That was my fault. We had some struggle with encoding and there were a lot of empty lanes in the Italian. It seems I mixed up the files while juggling with the files. Thank you for your work and sorry again!

**Comment by MrOgeid** [comment]
Don't worry @TheVaan! 👍 For the empty lines what can I do? I noticed some double empty lines between some blocks of strings.

**Comment by MrOgeid** [comment]
And another question about the translation: I noticed that in the app the months in the Stagionality panel in the fishes and insects's cards are displayed in English. (In all the languages). Do they need a manual translation?

**Comment by TheVaan** [comment]
This depends on the editor you use. I think the problem is resolved by setting line ending explict. In your new commit there aren't any empty lines that shouldn't be there.

We don't need a manual translation for the shorted month in the critter view. We need to fix the code there. I'll take a look on this later. See #232

**Comment by MrOgeid** [comment]
Thanks for the explanation on the empty lines! Probably I made a mistake in a previous commit!😅

**Comment by TheVaan** [comment]
Just wanted to let you know: I implemented automatic localization of month name in critter seasonality view

**Comment by MrOgeid** [comment]
Awesome!👍 Thanks!

**Pull request merged**
