### PR TITLE
Add Japanese Localization

### PR DESCRIPTION
**Pull request by mimikun**
This is Draft.

### CODE REVIEW

**Comment by Dimillian** [comment]
If you merge master with your branch you'll have items in japanese now :) 
https://github.com/Dimillian/ACHNBrowserUI/commit/50baff368ebb9f45ed8cb7c3e5cc2e5199aba803

Screenshot 2020-05-14 at 16 02 40

**Comment by Dimillian** [comment]
This is really awesome progress. Can't wait to ship it in an update :)

**Comment by mimikun** [comment]
Thank you for waiting.

There is an untranslated part, but I was unsure of the nuances, so I skipped it.

**Comment by Dimillian** [comment]
Perfect :) I'll try to notify you of the missing keys. Will be in the next update! Could you also take a look at the App Store metas? If we could have the App Store description / subtitle translated it would have a big impact on your App Store :) https://github.com/Dimillian/ACHNBrowserUI/tree/master/app-store/metada

**Comment by mimikun** [comment]
Thanks! I'll try AppStore metadata translate.
Would you tell me how to preview AppStore metadata ?
It's difficult to translate if you don't know how it actually looks...

**Pull request merged**
