### PR TITLE
Turnip prices should update to show user input

### PR DESCRIPTION
**Pull request by maeganjwilson**
This is work for issue #110. It doesn't include localizations, but conditionally shows turnip prices. I just took a crack at it and try to match the style of the app already.

### CODE REVIEW

**Comment by Dimillian** [comment]
I'm really not sure about that. Maybe the text should be more explicit? Like "Your in game price this morning is X and the predictions for this afternoon is Y". Right now it feels weird.

**Comment by Dimillian** [comment]
@TheVaan @renaudjenny on this.

**Comment by TheVaan** [comment]
I agree that it’s not that easy to find the right text. When we touch the text, we should discuss if there is more to do. 
E.g. it doesn’t make sense to show the average price in the morning when it is later then 12pm and you inserted prices for the afternoon. 
Maybe we need steps like:
- no values for today:
  Your in game price is predicted to be around X in the morning and around Y in the afternoon
- value morning inserted, value afternoon missing
  Your in game price was X in the morning and is predicted to be around Y in the afternoon
- value in the afternoon inserted (doesn’t matter if morning value inserted)
  Your in game price tomorrow is predicted to be around X in the morning and around Y in the afternoon

Just an idea.

**Comment by Dimillian** [comment]
I'm sorry we'll redo this one internally for now. Not yet clear on the features and I'm working on it to experiment.

**Pull request closed without merging**
