### PR TITLE
Turnip chart's legends size fix

### PR DESCRIPTION
**Pull request by Pyroh**
Legends now adapt to dynamic type.

### CODE REVIEW

**Comment by Dimillian** [comment]
Good to me too but @renaudjenny want to take a look tonight :)

**Comment by renaudjenny** [comment]
I checkouted your branch and tested it, it's working nicely!
Well done :). I'm still reading and understanding how Anchor Preference are working thanks to this article: https://swiftwithmajid.com/2020/03/18/anchor-preferences-in-swiftui/. I'm maybe see some improvements already, but I can take for later.
I would suggest some refactoring as well (like putting nested `struct` inside an extension instead of being in the top of the View `struct`, but it's just code style and I can handle it myself in another PR.
Then approved 👍. Thank you @Pyroh!
@Dimillian you could merge when you want :). Thanks

**Comment by Pyroh** [comment]
If you want interesting resources on SwiftUI and particularly layout take a look at [SwiftUI-lab's articles](https://swiftui-lab.com/category/layout/), Objc.io's [Thinking in SwiftUI](https://www.objc.io/books/thinking-in-swiftui/) is also a recommended read. 

It may be tempting to refactor `PreferenceKey`s outside their embedding views but before doing it you must know why I did it this way. 
As `PreferenceKey` acts as a key for a view tree's preference list is must be unique for this tree. Let's say that you create an *all-purpose* `HeightPreferenceKey` in another file and use it like this :

```Swift
@State private var viewAHeight: CGFloat?
@State private var viewBHeight: CGFloat?

var body: some View {
    VStack {
        viewA().propagateHeight(HeightPreferenceKey.self)
        viewB().propagateHeight(HeightPreferenceKey.self)
    }
    .onHeightPreferenceChange(HeightPreferenceKey.self, storeValueIn: $viewAHeight)
    .onHeightPreferenceChange(HeightPreferenceKey.self, storeValueIn: $viewBHeight)
}
```

You will end-up with `viewAHeight == viewBHeight == <actual viewB height>`.

What you would need to do is to create `ViewAHeightPreferenceKey` and `ViewBHeightPreferenceKey`.  
Since these `PreferenceKey`s are tied to `ViewA` and `ViewB` I think it's better to embed these directly in the views' code. It's clearer (IMHO) to have a `ViewA.HeightPreferenceKey` rather than a `ViewAHeightPreferenceKey`. Its' something you will see in AppKit and UIKit with `NotificationName` for example.  

That's why I did it like this 😃

**Comment by renaudjenny** [comment]
No problems I completely followed you on that, my only concern is to just "extract" the declaration into an extension. Meaning:
```swift
struct TurnipsChartBottomLegendView: View {
    ....
}

extension TurnipsChartBottomLegenView {
    struct HeightPreferenceKey: PreferenceKey {
         static var defaultValue: CGFloat?
         static func reduce(value: inout CGFloat?, nextValue: () -> CGFloat?) {
             if let newValue = nextValue() { value = newValue }
        }
    }
}
```

instead of that
```swift
 struct TurnipsChartBottomLegendView: View {
     struct HeightPreferenceKey: PreferenceKey {
         static var defaultValue: CGFloat?
         static func reduce(value: inout CGFloat?, nextValue: () -> CGFloat?) {
             if let newValue = nextValue() { value = newValue }
        }
    }
    ...
}
```
That's pretty much only changes that I will made :).
Thanks for all articles, a lot of things to read indeed :D.

**Comment by renaudjenny** [comment]
btw, I really like your approach to simplify and abstract the complexity of all of this thanks to your `View` extension generic methods, that's clever 👍!

**Comment by Pyroh** [comment]
Oops it seems that I missed the point of you post, my bad 😅  

Regarding the the view extensions I think that's it's one of the more powerful things brought by SwiftUI. You can instantly extend all view types at once !

**Pull request merged**
